apiVersion: v1
kind: Service
metadata:
  name: sre-app-service
spec:
  selector:
    app: sre-app
  ports:
    - protocol: TCP
      port: 80         # Porta externa
      targetPort: 8080 # Porta interna do container
  type: LoadBalancer
